name: 'Setup build2'
description: 'Installs the build2 build system on the runner'
author: 'Fabian Meyer'
inputs:
  build2-version:
    description: 'Version spec of the version to use. Examples: 0.14.0'
    default: '0.14.0'
runs:
  using: "composite"
  steps:
    - run: mkdir -p ${{ runner.temp }}/build2-build
      shell: bash
      
    - run: curl -sSfO https://download.build2.org/${{ input.build2-version }}/build2-install-${{ input.build2-version }}.sh
      shell: bash
      working-directory: ${{ runner.temp }}/build2-build
      if: ${{ runner.os != 'Windows' }}
    - run: sudo sh build2-install-${{ build2-version }}.sh --yes
      shell: bash
      working-directory: ${{ runner.temp }}/build2-build
      if: ${{ runner.os != 'Windows' }}
    
    - run: curl -sSfO https://download.build2.org/${{ input.build2-version }}/build2-install-msvc-${{ input.build2-version }}.bat
      shell: bash
      working-directory: ${{ runner.temp }}/build2-build
      if: ${{ runner.os == 'Windows' }}
    - run: build2-install-msvc-0.14.0.bat
      shell: cmd
      working-directory: ${{ runner.temp }}/build2-build
      if: ${{ runner.os == 'Windows' }}
      
      
    
     
