name: 'Setup build2'
description: 'Installs the build2 build system on the runner'
author: 'Fabian Meyer'
inputs:
  build2-version:
    description: 'Version spec of the version to use. Examples: 0.14.0'
    default: '0.14.0'
runs:
  using: "composite"
  steps:
    - run: mkdir -p ${{ runner.temp }}/build2-build
      shell: bash
      if: ${{ runner.os != 'Windows' }}
    - run: curl -sSfO https://download.build2.org/${{ inputs.build2-version }}/build2-install-${{ inputs.build2-version }}.sh
      shell: bash
      working-directory: ${{ runner.temp }}/build2-build
      if: ${{ runner.os != 'Windows' }}
    - run: sudo sh build2-install-${{ inputs.build2-version }}.sh --yes --trust "70:64:FE:E4:E0:F3:60:F1:B4:51:E1:FA:12:5C:E0:B3:DB:DF:96:33:39:B9:2E:E5:C2:68:63:4C:A6:47:39:43"
      shell: bash
      working-directory: ${{ runner.temp }}/build2-build
      if: ${{ runner.os != 'Windows' }}
    - run: b --version
      shell: bash
      if: ${{ runner.os != 'Windows' }}
    - run: bdep --version
      shell: bash
      if: ${{ runner.os != 'Windows' }}
    - run: bpkg --version
      shell: bash
      if: ${{ runner.os != 'Windows' }}
    
    - run: New-Item -Path "${{ runner.temp }}\build2-build" -ItemType Directory
      shell: powershell
      if: ${{ runner.os == 'Windows' }}
    - run: Invoke-WebRequest -Uri "https://download.build2.org/${{ inputs.build2-version }}/build2-install-msvc-${{ inputs.build2-version }}.bat" -OutFile "build2-install-msvc-${{ inputs.build2-version }}.bat"
      shell: powershell
      working-directory: ${{ runner.temp }}\build2-build
      if: ${{ runner.os == 'Windows' }}
    - shell: powershell
      working-directory: ${{ runner.temp }}\build2-build
      if: ${{ runner.os == 'Windows' }}
      run: |
        $vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
        $vcvarspath = &$vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
        Write-Output "Found vc tools: $vcvarspath"
        cmd.exe /c "call `"$vcvarspath\VC\Auxiliary\Build\vcvars64.bat`" && .\build2-install-msvc-${{ inputs.build2-version }}.bat --yes --trust `"70:64:FE:E4:E0:F3:60:F1:B4:51:E1:FA:12:5C:E0:B3:DB:DF:96:33:39:B9:2E:E5:C2:68:63:4C:A6:47:39:43`""
        
        $oldpath = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
        $newpath = "$oldpath;C:\build2\bin"
        Write-Output "Path: $newpath"
        setx /M PATH "$newpath"
    - run: b --version
      shell: cmd
      if: ${{ runner.os == 'Windows' }}
    - run: bdep --version
      shell: cmd
      if: ${{ runner.os == 'Windows' }}
    - run: bpkg --version
      shell: cmd
      if: ${{ runner.os == 'Windows' }}
